source 'https://rubygems.org'

gem 'em-http-request', '~> 1.0'
gem 'erubis', '~> 2.7.0'
gem 'keen'
gem 'less'
gem 'minitest', '~>2.6.0', :require => 'minitest/autorun', :group => 'test'
gem 'oj'
gem 'openpgp'
gem 'rack-less', :require => 'rack/less'
gem 'rack-test', :require => 'rack/test', :group => 'test'
gem 'rake'
gem 'redcarpet'
gem 'rr', :group => 'test'
gem 'shotgun', :group => 'development'
gem 'sinatra', :require => 'sinatra/base'
gem 'therubyracer'
gem 'thin'
