source 'https://rubygems.org'

gem 'activerecord', '>= 3.1', :require => 'active_record'
gem 'erubis', '~> 2.7.0'
gem 'less'
gem 'minitest', '~>2.6.0', :require => 'minitest/autorun', :group => 'test'
gem 'oj'
gem 'padrino', :github => 'padrino/padrino-framework'
gem 'rack-less'
gem 'rack-test', :require => 'rack/test', :group => 'test'
gem 'rake'
gem 'rr', :group => 'test'
gem 'shotgun'
gem 'sqlite3'
gem 'therubyracer'
gem 'thin'
