source 'https://rubygems.org'

gem 'erubis', '~> 2.7.0'
gem 'less'
gem 'minitest', '~>2.6.0', :require => 'minitest/autorun', :group => 'test'
gem 'oj'
gem 'openpgp'
gem 'rack-less', :require => 'rack/less'
gem 'rack-test', :require => 'rack/test', :group => 'test'
gem 'rake'
gem 'rr', :group => 'test'
gem 'shotgun'
gem 'sinatra'
gem 'therubyracer'
gem 'thin'
